name: Bug Report
description: Report a bug or issue with the theme
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create slides with...
        2. Use layout...
        3. Run command...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Theme Version
      description: What version of slidev-theme-ebpf-vienna are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: input
    id: slidev-version
    attributes:
      label: Slidev Version
      description: What version of Slidev are you using?
      placeholder: e.g., 0.52.8
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node Version
      description: What version of Node.js are you using?
      placeholder: e.g., 24.4.0
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, error messages, etc.
